### ISSUE TITLE
[FEATURE] Planejamento da avaliação da Análise de Tarefas

### ISSUE THREAD

**Issue by nszchagas** [Interacao-Humano-Computador/2022.2-Lichess#56]
# Tarefas 
- [ ] Planejar a avaliação
- [x] Planejar o relato de resultados

# Critérios de aceitação
- [ ] O planejamento da avaliação segue o Framework DECIDE?
- [ ] Os objetivos da avaliação de IHC?
- [ ] As perguntas a serem respondidas com a avaliação? (Ver tabela XXX: Exemplos de perguntas que uma avaliação de IHC pode responder do livro de IHC da Simone).
- [ ] Os métodos de avaliação a serem utilizados?
- [ ] As questões práticas da avaliação (sobre o recrutamento dos usuários que participarão da avaliação (onde e o perfil), quantos usuários participarão da avaliação e a razão dessa quantidade, a preparação e o uso dos equipamentos necessários, os prazos; o orçamento; recursos de mão-de-obra necessária para conduzir a avaliação)?
- [ ] As questões éticas ( se os participantes da avaliação devem ser respeitados e não podem ser prejudicados direta ou indiretamente, nem durante os experimentos, nem após a divulgação dos resultados da avaliação.)?
- [ ] A estrutura do relatório da avaliação (os objetivos da avaliação; uma breve descrição do método de prototipação em papel; o número e o perfil de avaliadores e dos participantes; as tarefas executadas pelos participantes; lista de problemas encontrados etc)?
- [ ] Um cronograma (data e horário) e local para realização da avaliação do StoryBoard e da Análise das Tarefas?
- [ ] A realização de um teste piloto antes da avaliação?
- [ ] A definição do teste piloto?
- [ ] Os itens que o avaliador deve realizar/anotar durante a avaliação (listar os problemas encontrados, priorizar a correção dos problemas não resolvidos)?

**Comment by nszchagas** [comment]
Atenção, @lucasgabriel-2 e @MauricioMachadoFF, seguir o seguinte padrão na organização de pastas: 


```yml 
- Análise de Requisitos:
      - Aspectos éticos: "analise_requisitos/aspectos_eticos.md"
      - Princípios Gerais do Projeto: "analise_requisitos/principios_gerais.md"
      - Perfil de Usuário: "analise_requisitos/perfil_usuario.md"
      - Personas: "analise_requisitos/personas.md"
      - Metas de Usabilidade: "analise_requisitos/metas_usabilidade.md"
      - Mapa de Empatia: "analise_requisitos/mapa_empatia.md"
      - Análise de tarefas: "analise_requisitos/analise_tarefas.md"
      - Guia de Estilo: "analise_requisitos/guia_de_estilo.md"
  - Design, Avaliação e Desenvolvimento:
      - Nível 1:
          - Storyboard:
              - Planejamento da Avaliação: design_avaliacao_desenvolvimento/storyboard/planejamento_avaliacao.md
              - Planejamento do Relato de Resultados: design_avaliacao_desenvolvimento/storyboard/planejamento_relato.md
          - Análise de Tarefas:
              - Planejamento da Avaliação: design_avaliacao_desenvolvimento/analise_tarefas/planejamento_avaliacao.md
              - Planejamento do Relato de Resultados: design_avaliacao_desenvolvimento/analise_tarefas/planejamento_relato.md
  ``` 
mkdocs.yml
